"use client";

import { useSearchParams } from "next/navigation";
import { useAuth } from "@clerk/nextjs";
import { Suspense } from "react";

function TgAuthContent() {
  const searchParams = useSearchParams();
  const token = searchParams.get("token");
  const bot = searchParams.get("bot");
  const { userId, isLoaded } = useAuth();

  if (!isLoaded) {
    return <p>Loading session...</p>;
  }

  if (!token || !bot) {
    return (
      <main style={{ padding: "40px", fontFamily: "sans-serif", maxWidth: "600px", margin: "0 auto" }}>
        <h1>Telegram Link Error</h1>
        <p>Missing parameters. Please click the authentication link generated by your Telegram bot.</p>
      </main>
    );
  }

  if (!userId) {
    return <p>Sign-in required...</p>;
  }

  const telegramRedirectUrl = `https://t.me/${bot}?start=link_${userId}_${token}`;

  return (
    <main style={{ padding: "40px", fontFamily: "sans-serif", maxWidth: "600px", margin: "0 auto", textAlign: "center" }}>
      <h1>Link Telegram Account</h1>
      <p style={{ fontSize: "1.2rem", lineHeight: "1.5", marginBottom: "30px" }}>
        You are authenticated! Click the button below to link your OpenCai account with your Telegram chat.
      </p>
      <a
        href={telegramRedirectUrl}
        style={{
          display: "inline-block",
          padding: "12px 24px",
          backgroundColor: "#24A1DE",
          color: "#fff",
          textDecoration: "none",
          borderRadius: "8px",
          fontWeight: "bold",
          fontSize: "1.1rem"
        }}
      >
        Confirm and Open Telegram
      </a>
    </main>
  );
}

export default function TgAuthPage() {
  return (
    <Suspense fallback={<div style={{ padding: "40px" }}>Loading page...</div>}>
      <TgAuthContent />
    </Suspense>
  );
}
